language: java
jdk:
- oraclejdk8
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: "mnC3CNj9+oAHPMI2tR8KvXU0AlqQyt71vrtHGTGRK3TJclOXUqVVbhhqkOTEaiPJuXrEzA5WzdTA3anNVlWIFAPUYEoB43DtQE2+QAsDrL5H2HcrkmoW29+jMpCzljMJK/G+JmiVLcXFMCnAe7SofJkzQ/8go/2pRbdXH9iK7mjlFbTij40306OXh9rQFgZvZGmEqNriMduq2iVOLPlZiSNgL7MHDOuJ479sLNdllPe9d7K7TOPCDzIYyBnc917HJTK7+7ejODZKfqv3GMNgjtoB37kxYIm5IXn2LUnzVYjQ5RLJwKPX9rEcYjfQUKyxfE4A1Zx6eRQZbzTMju4Xmr+hXfuFI7wFgu4lFoD0bKPlJ9RSeTiGzeB24Yy2JAacNHpd8RNqhzcqHTv13Md9zeCFIRZIvpJbMlGy/EJHNXR+F94amui3fNJQR9/Ssv1z/qepZnkm7CGh6KWE21GYUBPol71aqAbDjji1TO/LU6eyM8RALlKlc+91p7RTkUUqJFAwa4IGZi5mKcHbGuXdsxIaa22mSgDSfAJ6VBjSSVJ+vJg/HjZpVmwn55F/iduwjjkUZ+b0KExCmjfumiAlCYKHuhmjr8tlgUvgQEq7LGqOXwxtKyXP6jl2P4xbx/U0DuGTGfO9A3JU/W7yJY7W83yLCG1QjGCXX6goTnm68pk="
  - secure: "GvXY/uBAC0jGMTZ8uuX6fTb4GEpONbTkDmzYePDnaHtdrgeZ6cG3iGbYC05wi3HQScvPF0gPh+HftZX8+Bz60MyuqXUVpLpDpfcyXGothMc6D6PDvsWxp6Dnzjy9u2OpDnoi0inalI/86/EpwVZYyloFTO/xnVbVNuU9NqZg5wOb/VcqGCUH+GiRpMJVDqkwTBHk1rYTDuG3vPtCjkZkO5UniIsndRKnwBqXy8FdSonAJF6HME/yElHUx3GHTfyu/vmfXqbWHxnAcIKmrQqLkz3lMaGVQSV7nhUGCDgJ58KnXkTtjLDVX+5H5wZwrLRI3tXNHdsSBNwgosJNOdFBteMyToocENsL83VT7j4ppj4etEqSd1JJFfMefnW/bSjCsyrsSYmzuwO6iQOVEbnCAscpY9rkextU1OLmHj6QOElZztR4Exj5WqfLOMgj5Ou5HmAG48q9kMJg6H7v1sgR4AEQ34dntioogc6bjjUc54d7GHcQhLXcSs3+kEhfu9NPJVuQt5NkAenT1UkXSWl+r5DoFnGTjxHWrRpQU6YffB6A31gj+bSdMmFuTa4QXgssD6Y0N0LvowHJA+vw8baTvOYl/vw+Ft9Ak7YtFwqY2zqwQVWqp/6spOPdjds4jaSedw66BtDi1HtpwE0hMQlG5kvh9/ICFLNmpzDLUp/m2EU="
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
