language: java
jdk:
- oraclejdk8
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: "df7SKVSiveNWbtABAIpA96KKLvZQVc+lV9Rg38dEihI07QZLiLgUOu1adjak/AbexZKUkdDyYJnQFXprguum57jaon4bsVrIQSQqxyO+U2JSCjmpD0HyYM+PYsFCtYJvChsx6ftWNfcl/T71FbsAb3Rrco9I7ejwRQjeYMzZyP4r7usOBmazB4CStNl1inaN5fAPp66JpEzXFCAUSdwYCjO6ZlGHcoFzYbWLcW5LTnNHMuX47D6I46nBVtWEmj5dJnTCbb7AOOarQKYlR9g+qpicT1R+udpgAi/mfEV38LfxQx3I1wo4NsV/aEqiKarajRgccJ19LIlxbY4GC/jEcv/xKsz1z88K4sCwUW3nFT7jeQEiiAdK+yJS4GEwfQRtvD73TQu0mrL2SySObhRtiqSS/RY98vUNtNkLGXqYIgc5i3/+bY0N1hPs1k8RmMBeJChCVAUMVqbMbStiUzxnzNEthRUij0IySd9HZnQnVzALJgl+CcP2mDqEOPvk9repD+BOObzwGHpgtziPLhsLkjy9fiUYolcOOymyEGzDgjgYgYwEDfoIei7OwUHfGNS+ojxvQsy1zl/1UCjRxvd0z6dwUOZFu0PrXGRVZgM29R+GL0bixBUSdRu5ooUoPeP7mvMxuDtUDv7Wt3eaFErWzYjcSFvkz7p5EZQW0cLzpT0="
  - secure: "GvXY/uBAC0jGMTZ8uuX6fTb4GEpONbTkDmzYePDnaHtdrgeZ6cG3iGbYC05wi3HQScvPF0gPh+HftZX8+Bz60MyuqXUVpLpDpfcyXGothMc6D6PDvsWxp6Dnzjy9u2OpDnoi0inalI/86/EpwVZYyloFTO/xnVbVNuU9NqZg5wOb/VcqGCUH+GiRpMJVDqkwTBHk1rYTDuG3vPtCjkZkO5UniIsndRKnwBqXy8FdSonAJF6HME/yElHUx3GHTfyu/vmfXqbWHxnAcIKmrQqLkz3lMaGVQSV7nhUGCDgJ58KnXkTtjLDVX+5H5wZwrLRI3tXNHdsSBNwgosJNOdFBteMyToocENsL83VT7j4ppj4etEqSd1JJFfMefnW/bSjCsyrsSYmzuwO6iQOVEbnCAscpY9rkextU1OLmHj6QOElZztR4Exj5WqfLOMgj5Ou5HmAG48q9kMJg6H7v1sgR4AEQ34dntioogc6bjjUc54d7GHcQhLXcSs3+kEhfu9NPJVuQt5NkAenT1UkXSWl+r5DoFnGTjxHWrRpQU6YffB6A31gj+bSdMmFuTa4QXgssD6Y0N0LvowHJA+vw8baTvOYl/vw+Ft9Ak7YtFwqY2zqwQVWqp/6spOPdjds4jaSedw66BtDi1HtpwE0hMQlG5kvh9/ICFLNmpzDLUp/m2EU="
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
